services:
  server:
    build: ./server
    env_file: ./server/.env
    ports: ["4000:4000"]
    volumes:
      - ./server/uploads:/app/uploads
  client:
    build: ./client
    environment:
      - VITE_API_BASE=http://localhost:4000/api
    ports: ["5173:5173"]
  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports: ["8080:80"]
    depends_on:
      - server
      - client
